export interface GameWord {
  word: string;
  hint: string;
}

export const CATEGORIES = [
  {
    id: 'foods',
    name: 'Comidas',
    icon: '🍔',
    color: 'from-orange-500 to-red-600',
    words: [
      { word: 'Pizza', hint: 'Disco fraccionado' },
      { word: 'Sushi', hint: 'Mar crudo' },
      { word: 'Hamburguesa', hint: 'Carnívoro apilado' },
      { word: 'Tacos', hint: 'Doblado ancestral' },
      { word: 'Pasta', hint: 'Geometría hervida' },
      { word: 'Asado', hint: 'Ritual de brasas' },
      { word: 'Paella', hint: 'Sartén amarilla' },
      { word: 'Ramen', hint: 'Caldo alcalino' },
      { word: 'Ensalada', hint: 'Caos verde' },
      { word: 'Helado', hint: 'Cristal dulce' },
      { word: 'Lasaña', hint: 'Pisos de salsa' },
      { word: 'Ceviche', hint: 'Cocción cítrica' },
      { word: 'Risotto', hint: 'Cremosidad de grano' },
      { word: 'Milanesa', hint: 'Dorado empanado' },
      { word: 'Tarta', hint: 'Molde cerrado' },
      { word: 'Polenta', hint: 'Maíz espeso' },
      { word: 'Hot Dog', hint: 'Salchicha abrigada' },
      { word: 'Waffles', hint: 'Rejilla tostada' },
      { word: 'Papas Fritas', hint: 'Bastones dorados' },
      { word: 'Puré', hint: 'Textura aplastada' },
      { word: 'Sopa', hint: 'Calor de cuchara' },
      { word: 'Guiso', hint: 'Olla invernal' },
      { word: 'Tortilla', hint: 'Giro de sartén' },
      { word: 'Kebab', hint: 'Espada giratoria' },
      { word: 'Falafel', hint: 'Esfera de garbanzo' },
      { word: 'Hummus', hint: 'Crema del desierto' },
      { word: 'Curry', hint: 'Especias ardientes' },
      { word: 'Pad Thai', hint: 'Salteado tailandés' },
      { word: 'Bruschetta', hint: 'Tostada perfumada' },
      { word: 'Carpaccio', hint: 'Láminas crudas' },
      { word: 'Fondue', hint: 'Caldero fundido' },
      { word: 'Churros', hint: 'Estrella frita' },
      { word: 'Donas', hint: 'Anillo glaseado' },
      { word: 'Cheesecake', hint: 'Queso horneado' },
      { word: 'Brownie', hint: 'Cuadrado denso' },
      { word: 'Tiramisú', hint: 'Capas de café' },
      { word: 'Flan', hint: 'Temblor de caramelo' },
      { word: 'Macarons', hint: 'Cúpulas parisinas' },
      { word: 'Croissant', hint: 'Luna hojaldrada' },
      { word: 'Sándwich', hint: 'Entre dos panes' },
      { word: 'Shawarma', hint: 'Rollo especiado' },
      { word: 'Burrito', hint: 'Manta mexicana' },
      { word: 'Quesadilla', hint: 'Doble de queso' },
      { word: 'Nachos', hint: 'Triángulos crujientes' },
      { word: 'Guacamole', hint: 'Verde machacado' },
      { word: 'Ñoquis', hint: 'Veintinueve del calendario' },
      { word: 'Sorrentinos', hint: 'Sombreros rellenos' },
      { word: 'Ravioles', hint: 'Almohadillas de masa' },
      { word: 'Canelones', hint: 'Tubos gratinados' },
      { word: 'Empanadas', hint: 'Repulgue horneado' },
      { word: 'Crepe', hint: 'Lienzo enrollado' },
      { word: 'Gazpacho', hint: 'Caldo frío' },
      { word: 'Tarta de Manzana', hint: 'Fruta horneada' },
      { word: 'Arepa', hint: 'Disco de maíz' },
      { word: 'Tequeños', hint: 'Dedos de queso' },
      { word: 'Omelette', hint: 'Huevo doblado' },
      { word: 'Humita', hint: 'Chala rellena' },
      { word: 'Tamal', hint: 'Masa envuelta' },
      { word: 'Panqueques', hint: 'Torre con dulce' },
      { word: 'Tacos al Pastor', hint: 'Trompo mexicano' }
    ] as GameWord[]
  },
  {
    id: 'sports',
    name: 'Deportes',
    icon: '🏆',
    color: 'from-blue-500 to-indigo-600',
    words: [
      { word: 'Fútbol', hint: 'Veintidós persiguiendo' },
      { word: 'Tenis', hint: 'Cero es amor' },
      { word: 'Básquet', hint: 'Red sin fondo' },
      { word: 'Golf', hint: 'Caminata arruinada' },
      { word: 'Natación', hint: 'Batalla acuática' },
      { word: 'Boxeo', hint: 'Baile violento' },
      { word: 'Rugby', hint: 'Pase inverso' },
      { word: 'Vóley', hint: 'Suelo prohibido' },
      { word: 'Ciclismo', hint: 'Giroscopio humano' },
      { word: 'Automovilismo', hint: 'Fuerza G' },
      { word: 'Atletismo', hint: 'Carrera de humanos' },
      { word: 'Béisbol', hint: 'Bate y diamante' },
      { word: 'Hockey', hint: 'Disco o bocha' },
      { word: 'Handball', hint: 'Fútbol con manos' },
      { word: 'Waterpolo', hint: 'Natación con arco' },
      { word: 'Esquí', hint: 'Deslizamiento blanco' },
      { word: 'Snowboard', hint: 'Tabla de nieve' },
      { word: 'Surf', hint: 'Cabalgando olas' },
      { word: 'Skateboarding', hint: 'Cuatro ruedas urbanas' },
      { word: 'Escalada', hint: 'Desafío vertical' },
      { word: 'Esgrima', hint: 'Duelo de caballeros' },
      { word: 'Judo', hint: 'Camino de suavidad' },
      { word: 'Karate', hint: 'Mano vacía' },
      { word: 'Taekwondo', hint: 'Camino de patadas' },
      { word: 'Remo', hint: 'Fuerza en el agua' },
      { word: 'Vela', hint: 'Viento y mástil' },
      { word: 'Kayak', hint: 'Pala de doble hoja' },
      { word: 'Motociclismo', hint: 'Dos ruedas veloces' },
      { word: 'Polo', hint: 'Taco sobre caballo' },
      { word: 'Squash', hint: 'Pared veloz' },
      { word: 'Badminton', hint: 'Pluma voladora' },
      { word: 'Tenis de Mesa', hint: 'Ping pong veloz' },
      { word: 'Ajedrez', hint: 'Guerra intelectual' },
      { word: 'Billar', hint: 'Taco y tronera' },
      { word: 'Dardos', hint: 'Diana de precisión' },
      { word: 'Tiro con Arco', hint: 'Flecha al centro' },
      { word: 'Gimnasia', hint: 'Flexibilidad artística' },
      { word: 'Patinaje', hint: 'Deslizamiento artístico' },
      { word: 'CrossFit', hint: 'Esfuerzo extremo' },
      { word: 'Triatlón', hint: 'Tres disciplinas unidas' },
      { word: 'Pentatlón', hint: 'Cinco pruebas clásicas' },
      { word: 'Halterofilia', hint: 'Fuerza de hierro' },
      { word: 'Lucha Libre', hint: 'Máscaras en el cuadrilátero' },
      { word: 'Críquet', hint: 'Bate de madera plana' },
      { word: 'Lacrosse', hint: 'Red atrapadora' },
      { word: 'Curling', hint: 'Piedra sobre hielo' },
      { word: 'Bobsleigh', hint: 'Trineo supersónico' },
      { word: 'Motocross', hint: 'Saltos de tierra' },
      { word: 'Padel', hint: 'Paredes de cristal' },
      { word: 'Kickboxing', hint: 'Puño y patada' },
      { word: 'Softbol', hint: 'Hermano del béisbol' },
      { word: 'Rafting', hint: 'Turbulencia fluvial' },
      { word: 'Windsurf', hint: 'Vela sobre tabla' },
      { word: 'Kitesurf', hint: 'Cometa veloz' },
      { word: 'Wakeboard', hint: 'Esquí con tabla' },
      { word: 'Paracaidismo', hint: 'Caída libre' },
      { word: 'Parapente', hint: 'Vuelo sin motor' },
      { word: 'Alpinismo', hint: 'Corona de cumbres' },
      { word: 'Senderismo', hint: 'Caminata natural' },
      { word: 'Pesca', hint: 'Silencio y anzuelo' }
    ] as GameWord[]
  },
  {
    id: 'footballers',
    name: 'Futbolistas',
    icon: '⚽',
    color: 'from-green-500 to-emerald-700',
    words: [
      { word: 'Cristiano Ronaldo', hint: 'Salto y grito' },
      { word: 'Neymar', hint: 'Magia y danza' },
      { word: 'Mbappe', hint: 'Velocidad gala' },
      { word: 'Haaland', hint: 'Androide nórdico' },
      { word: 'Benzema', hint: 'Gato francés' },
      { word: 'Lewandowski', hint: 'Máquina polaca' },
      { word: 'Modric', hint: 'Eternidad croata' },
      { word: 'De Bruyne', hint: 'Precisión belga' },
      { word: 'Vinicius Jr', hint: 'Gambeta joven' },
      { word: 'Ronaldinho', hint: 'Magia alegre' },
      { word: 'Lionel Messi', hint: 'Zurda rosarina' },
      { word: 'Diego Maradona', hint: 'Barrilete cósmico' },
      { word: 'Pele', hint: 'O rei brasileño' },
      { word: 'Zinedine Zidane', hint: 'Ruleta marsellesa' },
      { word: 'Ronaldo Nazario', hint: 'El fenómeno brasileño' },
      { word: 'Johan Cruyff', hint: 'Giro holandés' },
      { word: 'Franz Beckenbauer', hint: 'El kaiser defensor' },
      { word: 'Michel Platini', hint: 'Diez francés' },
      { word: 'Zlatan Ibrahimovic', hint: 'Dios de taquito' },
      { word: 'Luis Suárez', hint: 'Pistolero uruguayo' },
      { word: 'Edinson Cavani', hint: 'Matador uruguayo' },
      { word: 'Antoine Griezmann', hint: 'Principito colchonero' },
      { word: 'Toni Kroos', hint: 'Francotirador bávaro' },
      { word: 'Sergio Ramos', hint: 'Héroe del noventa y tres' },
      { word: 'Gerard Piqué', hint: 'Presidente de reyes' },
      { word: 'Iker Casillas', hint: 'Santo de madrid' },
      { word: 'Gianluigi Buffon', hint: 'Muro eterno' },
      { word: 'Manuel Neuer', hint: 'Líbero con guantes' },
      { word: 'Angel Di Maria', hint: 'Fideo decisivo' },
      { word: 'Roberto Baggio', hint: 'Coleta divina' },
      { word: 'Roberto Carlos', hint: 'Cañón de tres dedos' },
      { word: 'Kaka', hint: 'Último mortal' },
      { word: 'Thierry Henry', hint: 'Elegancia gunner' },
      { word: 'Didier Drogba', hint: 'Orgullo de costa de marfil' },
      { word: 'Samuel Eto\'o', hint: 'León indomable' },
      { word: 'Wayne Rooney', hint: 'Bad boy inglés' },
      { word: 'Steven Gerrard', hint: 'Capitán de anfield' },
      { word: 'Frank Lampard', hint: 'Goleador blue' },
      { word: 'Andrea Pirlo', hint: 'Maestro de seda' },
      { word: 'Francesco Totti', hint: 'Il capitano eterno' },
      { word: 'Alessandro Del Piero', hint: 'Pinturicchio juventino' },
      { word: 'Paolo Maldini', hint: 'Elegancia defensiva' },
      { word: 'Cafu', hint: 'Banda derecha interminable' },
      { word: 'Dani Alves', hint: 'Coleccionista de copas' },
      { word: 'Marcelo', hint: 'Magia de lateral' },
      { word: 'Sergio Busquets', hint: 'Silencioso del medio' },
      { word: 'Xavi Hernandez', hint: 'Cerebro de terrassa' },
      { word: 'Andres Iniesta', hint: 'Héroe de johannesburgo' },
      { word: 'David Beckham', hint: 'Guante inglés' },
      { word: 'Harry Kane', hint: 'Huracán de gol' },
      { word: 'Jude Bellingham', hint: 'El nuevo rey inglés' },
      { word: 'Sadio Mane', hint: 'Corazón senegalés' },
      { word: 'Mohamed Salah', hint: 'Faraón de anfield' },
      { word: 'Heung Min Son', hint: 'Sonrisa coreana' },
      { word: 'Luis Díaz', hint: 'Guajiro de Liverpool' },
      { word: 'Alexis Sánchez', hint: 'Niño maravilla' },
      { word: 'Arturo Vidal', hint: 'Rey Arturo' },
      { word: 'James Rodríguez', hint: 'Diez de Brasil catorce' },
      { word: 'Radamel Falcao', hint: 'Tigre de santa marta' },
      { word: 'Keylor Navas', hint: 'Halcón tico' }
    ] as GameWord[]
  },
  {
    id: 'movies',
    name: 'Películas',
    icon: '🎬',
    color: 'from-purple-500 to-pink-600',
    words: [
      { word: 'Titanic', hint: 'Hielo arrogante' },
      { word: 'Star Wars', hint: 'Tragedia galáctica' },
      { word: 'Avengers', hint: 'Disfuncionales unidos' },
      { word: 'El Padrino', hint: 'Oferta irrechazable' },
      { word: 'Shrek', hint: 'Cebolla verde' },
      { word: 'Inception', hint: 'Trompo infinito' },
      { word: 'Joker', hint: 'Escalera caótica' },
      { word: 'Avatar', hint: 'Cuerpos azules' },
      { word: 'Toy Story', hint: 'Suela marcada' },
      { word: 'Rocky', hint: 'Escalones triunfales' },
      { word: 'Gladiator', hint: 'Espada romana' },
      { word: 'Jurassic Park', hint: 'Dinosaurios clonados' },
      { word: 'El Señor de los Anillos', hint: 'Anillo único' },
      { word: 'Harry Potter', hint: 'Cicatriz de rayo' },
      { word: 'Matrix', hint: 'Píldora roja' },
      { word: 'Interestelar', hint: 'Gravedad y tiempo' },
      { word: 'El Caballero de la Noche', hint: 'Murciélago nocturno' },
      { word: 'Pulp Fiction', hint: 'Maletín misterioso' },
      { word: 'Bastardos Sin Gloria', hint: 'Caza de oficiales' },
      { word: 'Django Unchained', hint: 'Venganza sureña' },
      { word: 'Forrest Gump', hint: 'Caja de bombones' },
      { word: 'Cadena de Perpetua', hint: 'Pica de piedra' },
      { word: 'El Club de la Pelea', hint: 'Regla número uno' },
      { word: 'El Resplandor', hint: 'Hacha sangrienta' },
      { word: 'Psicosis', hint: 'Ducha mortal' },
      { word: 'Tiburón', hint: 'Aleta asesina' },
      { word: 'Alien', hint: 'Octavo pasajero' },
      { word: 'Depredador', hint: 'Camuflaje invisible' },
      { word: 'Terminator', hint: 'Volveré' },
      { word: 'Robocop', hint: 'Mitad máquina' },
      { word: 'Volver al Futuro', hint: 'Auto de tiempo' },
      { word: 'Cazafantasmas', hint: 'Mochila de protones' },
      { word: 'Indiana Jones', hint: 'Látigo y sombrero' },
      { word: 'Piratas del Caribe', hint: 'Brújula rota' },
      { word: 'Up', hint: 'Globos de colores' },
      { word: 'Buscando a Nemo', hint: 'Dirección de Sídney' },
      { word: 'Coco', hint: 'Guitarra blanca' },
      { word: 'Monstruos S.A.', hint: 'Puerta de gritos' },
      { word: 'Cars', hint: 'Copa Pistón' },
      { word: 'El Rey León', hint: 'Ciclo sin fin' },
      { word: 'Ratatouille', hint: 'Chef minúsculo' },
      { word: 'Wall-E', hint: 'Compactador espacial' },
      { word: 'Los Increíbles', hint: 'Trajes elásticos' },
      { word: 'Madagascar', hint: 'Selva neoyorquina' },
      { word: 'La La Land', hint: 'Baile en el cielo' },
      { word: 'Whiplash', hint: 'Ritmo de sangre' },
      { word: 'El Cisne Negro', hint: 'Plumas oscuras' },
      { word: 'Parásitos', hint: 'Sótano coreano' },
      { word: 'El Viaje de Chihiro', hint: 'Padres convertidos' },
      { word: 'Mi Vecino Totoro', hint: 'Paraguas gigante' },
      { word: 'El Padrino II', hint: 'Continuación gloriosa' },
      { word: 'King Kong', hint: 'Simio gigante' },
      { word: 'Casablanca', hint: 'Siempre nos quedará' },
      { word: 'Scarface', hint: 'Cara cortada' },
      { word: 'El Gran Truco', hint: 'Magos rivales' },
      { word: 'El Club de los Poetas Muertos', hint: 'Carpe diem' },
      { word: 'La Lista de Schindler', hint: 'Lista de vidas' },
      { word: 'Salvar al Soldado Ryan', hint: 'Día D' },
      { word: 'Kill Bill', hint: 'Espada amarilla' },
      { word: 'Sin Lugar para los Débiles', hint: 'Moneda del destino' }
    ] as GameWord[]
  },
  {
    id: 'countries',
    name: 'Países',
    icon: '🌎',
    color: 'from-emerald-500 to-teal-600',
    words: [
      { word: 'Argentina', hint: 'Tres estrellas' },
      { word: 'España', hint: 'Toros y sol' },
      { word: 'Japón', hint: 'Sol naciente' },
      { word: 'Italia', hint: 'Bota antigua' },
      { word: 'Brasil', hint: 'Verdeamarelo' },
      { word: 'Francia', hint: 'Hierro y luz' },
      { word: 'México', hint: 'Inframundo festivo' },
      { word: 'Alemania', hint: 'Muro caído' },
      { word: 'Canadá', hint: 'Hoja de arce' },
      { word: 'Australia', hint: 'Isla letal' },
      { word: 'Chile', hint: 'Larga franja' },
      { word: 'Uruguay', hint: 'Río de pájaros' },
      { word: 'Colombia', hint: 'Café andino' },
      { word: 'Perú', hint: 'Imperio del sol' },
      { word: 'Ecuador', hint: 'Mitad del mapa' },
      { word: 'Bolivia', hint: 'Tierra alta' },
      { word: 'Venezuela', hint: 'Salto de ángel' },
      { word: 'Paraguay', hint: 'Tierra de ríos' },
      { word: 'Costa Rica', hint: 'Pura vida' },
      { word: 'Cuba', hint: 'Azúcar e isla' },
      { word: 'Estados Unidos', hint: 'Barras y estrellas' },
      { word: 'Reino Unido', hint: 'Torre del reloj' },
      { word: 'Portugal', hint: 'Azulejos y fado' },
      { word: 'Países Bajos', hint: 'Molinos y tulipanes' },
      { word: 'Bélgica', hint: 'Chocolate y cómics' },
      { word: 'Suiza', hint: 'Relojes y Alpes' },
      { word: 'Austria', hint: 'Vals y música' },
      { word: 'Suecia', hint: 'Muebles y nieve' },
      { word: 'Noruega', hint: 'Fiordos norteños' },
      { word: 'Dinamarca', hint: 'Sirena del puerto' },
      { word: 'Islandia', hint: 'Hielo y fuego' },
      { word: 'Finlandia', hint: 'Lagos del norte' },
      { word: 'Rusia', hint: 'Plazas y cúpulas' },
      { word: 'China', hint: 'Gran muralla' },
      { word: 'India', hint: 'Taj Mahal' },
      { word: 'Corea del Sur', hint: 'K-pop y tecnología' },
      { word: 'Tailandia', hint: 'Elefantes y templos' },
      { word: 'Vietnam', hint: 'Bahía de rocas' },
      { word: 'Egipto', hint: 'Pirámides antiguas' },
      { word: 'Sudáfrica', hint: 'Arcoíris del sur' },
      { word: 'Marruecos', hint: 'Bazar y desierto' },
      { word: 'Kenia', hint: 'Safari salvaje' },
      { word: 'Nigeria', hint: 'Gigante verde' },
      { word: 'Senegal', hint: 'Paso del Dakar' },
      { word: 'Nueva Zelanda', hint: 'Tierra media' },
      { word: 'Grecia', hint: 'Templos blancos' },
      { word: 'Turquía', hint: 'Puente entre mundos' },
      { word: 'Arabia Saudita', hint: 'Tierra de arena' },
      { word: 'Irán', hint: 'Alfombras persas' },
      { word: 'Israel', hint: 'Tierra de olivos' },
      { word: 'Ucrania', hint: 'Trigo y girasoles' },
      { word: 'Polonia', hint: 'Castillos de ladrillo' },
      { word: 'Croacia', hint: 'Mil islas' },
      { word: 'República Checa', hint: 'Puente antiguo' },
      { word: 'Hungría', hint: 'Baños termales' },
      { word: 'Irlanda', hint: 'Duendes verdes' },
      { word: 'Escocia', hint: 'Gaita y monstruo' },
      { word: 'Gales', hint: 'Dragón rojo' },
      { word: 'Jamaica', hint: 'Reggae y velocidad' },
      { word: 'Bahamas', hint: 'Playas turquesas' }
    ] as GameWord[]
  },
  {
    id: 'anime',
    name: 'Anime',
    icon: '🐉',
    color: 'from-yellow-400 to-orange-500',
    words: [
      { word: 'Dragon Ball', hint: 'Siete esferas' },
      { word: 'Naruto', hint: 'Zorro sellado' },
      { word: 'One Piece', hint: 'Sombrero estirable' },
      { word: 'Death Note', hint: 'Tinta letal' },
      { word: 'Pokémon', hint: 'Roedor eléctrico' },
      { word: 'Attack on Titan', hint: 'Nuca vulnerable' },
      { word: 'Evangelion', hint: 'Trauma mecha' },
      { word: 'Demon Slayer', hint: 'Respiración solar' },
      { word: 'Sailor Moon', hint: 'Prisma lunar' },
      { word: 'Bleach', hint: 'Alma hueca' },
      { word: 'My Hero Academia', hint: 'Heredero de fuerza' },
      { word: 'Jujutsu Kaisen', hint: 'Dedos malditos' },
      { word: 'Chainsaw Man', hint: 'Motosierra en pecho' },
      { word: 'Fullmetal Alchemist', hint: 'Ley del intercambio' },
      { word: 'Hunter x Hunter', hint: 'Examen de cazador' },
      { word: 'Tokyo Ghoul', hint: 'Máscara parcheada' },
      { word: 'One Punch Man', hint: 'Golpe único' },
      { word: 'Mob Psycho 100', hint: 'Poder psíquico' },
      { word: 'JoJo\'s Bizarre Adventure', hint: 'Linaje de estrellas' },
      { word: 'Sword Art Online', hint: 'Atrapado en el juego' },
      { word: 'Steins;Gate', hint: 'Microondas temporal' },
      { word: 'Code Geass', hint: 'Ojo de obediencia' },
      { word: 'Gurren Lagann', hint: 'Taladro gigante' },
      { word: 'Kill la Kill', hint: 'Tijera roja' },
      { word: 'Cyberpunk Edgerunners', hint: 'Implante militar' },
      { word: 'Vinland Saga', hint: 'Venganza vikinga' },
      { word: 'Monster', hint: 'Doctor y monstruo' },
      { word: 'Death Parade', hint: 'Juego del juicio' },
      { word: 'Shigatsu wa Kimi no Uso', hint: 'Melodía de abril' },
      { word: 'Kimi no Na wa', hint: 'Nombres cruzados' },
      { word: 'Spirited Away', hint: 'Baño de espíritus' },
      { word: 'Princess Mononoke', hint: 'Lobo y bosque' },
      { word: 'Akira', hint: 'Moto roja' },
      { word: 'Ghost in the Shell', hint: 'Cerebro cibernético' },
      { word: 'Cowboy Bebop', hint: 'Jazz espacial' },
      { word: 'Samurai Champloo', hint: 'Hip hop y espadas' },
      { word: 'Hellsing', hint: 'Vampiro de rojo' },
      { word: 'Fate/Zero', hint: 'Santo Grial' },
      { word: 'Black Clover', hint: 'Grimorio de cinco' },
      { word: 'Fairy Tale', hint: 'Fuego de dragón' },
      { word: 'Gintama', hint: 'Parodia samurái' },
      { word: 'Noragami', hint: 'Dios de cinco yenes' },
      { word: 'Haikyuu', hint: 'Cuervo volador' },
      { word: 'Kuroko no Basket', hint: 'Sombra y luz' },
      { word: 'Slam Dunk', hint: 'Cesta de rebote' },
      { word: 'Blue Lock', hint: 'Prisión de goleadores' },
      { word: 'Hajime no Ippo', hint: 'Gancho de hígado' },
      { word: 'Saint Seiya', hint: 'Armadura de bronce' },
      { word: 'Yu-Gi-Oh!', hint: 'Duelo de cartas' },
      { word: 'Digimon', hint: 'Monstruos digitales' },
      { word: 'Black Butler', hint: 'Contrato de ojos' },
      { word: 'Claymore', hint: 'Ojos plateados' },
      { word: 'Berserk', hint: 'Espada negra' },
      { word: 'Fire Force', hint: 'Bomberos de fuego' },
      { word: 'Dr. Stone', hint: 'Edad de piedra' },
      { word: 'Overlord', hint: 'Esqueleto supremo' },
      { word: 'Re:Zero', hint: 'Muerte y retorno' },
      { word: 'Shield Hero', hint: 'Héroe del escudo' },
      { word: 'Konosuba', hint: 'Diosa inútil' },
      { word: 'Promised Neverland', hint: 'Huérfanos fugitivos' }
    ] as GameWord[]
  },
  {
    id: 'argentina',
    name: 'Argentina',
    icon: '🧉',
    color: 'from-sky-400 to-blue-600',
    words: [
      { word: 'Asado', hint: 'Aplauso al fuego' },
      { word: 'Mate', hint: 'Lavado y cebado' },
      { word: 'Messi', hint: 'Zurda qatarí' },
      { word: 'Maradona', hint: 'Mano divina' },
      { word: 'Tango', hint: 'Tristeza bailada' },
      { word: 'Obelisco', hint: 'Aguja céntrica' },
      { word: 'Fernet', hint: 'Amargo cordobés' },
      { word: 'Empanadas', hint: 'Repulgue oculto' },
      { word: 'Dulce de Leche', hint: 'Hervor marrón' },
      { word: 'Alfajor', hint: 'Arquitectura dulce' },
      { word: 'Charly García', hint: 'Lentes bicolor' },
      { word: 'Luis Alberto Spinetta', hint: 'Flaco de cristal' },
      { word: 'Gustavo Cerati', hint: 'Gracias totales' },
      { word: 'Mercedes Sosa', hint: 'Voz de américa' },
      { word: 'Quino', hint: 'Mafalda y sopa' },
      { word: 'Jorge Luis Borges', hint: 'Laberintos de biblioteca' },
      { word: 'René Favaloro', hint: 'Bypass del corazón' },
      { word: 'San Martín', hint: 'Cruce de Andes' },
      { word: 'Belgrano', hint: 'Creador de bandera' },
      { word: 'Fangio', hint: 'Cinco veces corona' },
      { word: 'Ginóbili', hint: 'La mano de Manu' },
      { word: 'Del Potro', hint: 'Torre de Tandil' },
      { word: 'Luciana Aymar', hint: 'Maga del hockey' },
      { word: 'Vilas', hint: 'Raqueta legendaria' },
      { word: 'Monzón', hint: 'Puños santafesinos' },
      { word: 'De Vicenzo', hint: 'Caballero del golf' },
      { word: 'Sabatini', hint: 'Flor del tenis' },
      { word: 'Gatica', hint: 'El mono del ring' },
      { word: 'Palermo', hint: 'Optimista del gol' },
      { word: 'Riquelme', hint: 'El último diez' },
      { word: 'La Bombonera', hint: 'Templo de latidos' },
      { word: 'El Monumental', hint: 'Casa de River' },
      { word: 'Caminito', hint: 'Calle de colores' },
      { word: 'Bariloche', hint: 'Nieve y chocolate' },
      { word: 'Cataratas del Iguazú', hint: 'Garganta del Diablo' },
      { word: 'Glaciar Perito Moreno', hint: 'Hielo gigante' },
      { word: 'Mar del Plata', hint: 'Feliz de la costa' },
      { word: 'Humahuaca', hint: 'Cerro de colores' },
      { word: 'Ushuaia', hint: 'Fin del mundo' },
      { word: 'San Telmo', hint: 'Antigüedades y adoquines' },
      { word: 'Truco', hint: 'Flor y envido' },
      { word: 'Chinchón', hint: 'Cartas en orden' },
      { word: 'Escoba del 15', hint: 'Limpieza de mesa' },
      { word: 'Llama', hint: 'Animal andino' },
      { word: 'Cóndor', hint: 'Alas de montaña' },
      { word: 'Yaguareté', hint: 'Tigre americano' },
      { word: 'Hornero', hint: 'Casa de barro' },
      { word: 'Ceibo', hint: 'Flor nacional' },
      { word: 'Calafate', hint: 'Fruto patagónico' },
      { word: 'Quebracho', hint: 'Madera de hierro' },
      { word: 'Gauchito Gil', hint: 'Rojo milagroso' },
      { word: 'Difunta Correa', hint: 'Agua del desierto' },
      { word: 'Carlos Gardel', hint: 'Canta cada día mejor' },
      { word: 'Sandro', hint: 'Gitano del fuego' },
      { word: 'Fito Páez', hint: 'El amor después del' },
      { word: 'Andrés Calamaro', hint: 'Salmón del rock' },
      { word: 'Pappo', hint: 'Carpo del blues' },
      { word: 'Indio Solari', hint: 'Misa ricotera' },
      { word: 'Ricardo Darín', hint: 'Nueve reinas' },
      { word: 'Guillermo Francella', hint: 'Me rindo ante' }
    ] as GameWord[]
  },
  {
    id: 'streamers',
    name: 'Streamers',
    icon: '🎧',
    color: 'from-purple-600 to-indigo-800',
    words: [
      { word: 'Ibai', hint: 'Velada masiva' },
      { word: 'Auronplay', hint: 'Abdúzcan' },
      { word: 'ElRubius', hint: 'Decano de bloques' },
      { word: 'TheGrefg', hint: 'Contador eterno' },
      { word: 'Coscu', hint: 'Ejército del sur' },
      { word: 'Spreen', hint: 'Lentes oscuros' },
      { word: 'Juansguarnizo', hint: 'Cama icónica' },
      { word: 'Illojuan', hint: 'Acento auténtico' },
      { word: 'Ludwig', hint: 'Subathon infinito' },
      { word: 'xQc', hint: 'Rey hiperactivo' },
      { word: 'Kai Cenat', hint: 'Rey del Amp' },
      { word: 'Speed', hint: 'Energía ruidosa' },
      { word: 'Ninja', hint: 'Cabello azul' },
      { word: 'Asmongold', hint: 'Rey del MMO' },
      { word: 'shroud', hint: 'Precisión táctica' },
      { word: 'DrDisrespect', hint: 'Dos veces campeón' },
      { word: 'HasanAbi', hint: 'Política en pantalla' },
      { word: 'Amouranth', hint: 'Hot tub jacuzzi' },
      { word: 'Mizkif', hint: 'Caja de cartón' },
      { word: 'MoistCr1TiKaL', hint: 'Jesús de internet' },
      { word: 'Jerma985', hint: 'Fiebre psicópata' },
      { word: 'Tyler1', hint: 'Hiperactividad muscular' },
      { word: 'Disguised Toast', hint: 'Pan con gafas' },
      { word: 'LilyPichu', hint: 'Voz de anime' },
      { word: 'Sykkuno', hint: 'Mano en boca' },
      { word: 'QuarterJade', hint: 'Tiro preciso' },
      { word: 'Fuslie', hint: 'Comunidad de fresas' },
      { word: 'TinaKitten', hint: 'Dibujos tiernos' },
      { word: 'Momo', hint: 'Poder de platense' },
      { word: 'Robleis', hint: 'Canción y risa' },
      { word: 'Brunenger', hint: 'Música y coche' },
      { word: 'Davoo Xeneize', hint: 'Camiseta de Boca' },
      { word: 'Luquita Rodriguez', hint: 'Teoría del sabor' },
      { word: 'German Garmendia', hint: 'Hola soy' },
      { word: 'Elish', hint: 'Pintora de Twitch' },
      { word: 'Rivers GG', hint: 'La patrona mexicana' },
      { word: 'Quackity', hint: 'Pato bilingüe' },
      { word: 'MissaSinfonia', hint: 'Cabello largo rockero' },
      { word: 'El Mariana', hint: 'Largo y asustadizo' },
      { word: 'Ari Gameplays', hint: 'Espejo rosa' },
      { word: 'BarcaGamer', hint: 'Lentes y barba' },
      { word: 'RobertoCein', hint: 'Rana mexicana' },
      { word: 'Cry', hint: 'Acento español oscuro' },
      { word: 'Pipepunk', hint: 'Punk mexicano' },
      { word: 'Aldo Geo', hint: 'Minecraft y risas' },
      { word: 'Roier', hint: 'Minecraft y comedia' },
      { word: 'Kameto', hint: 'Karmine Corp' },
      { word: 'DjMaRiiO', hint: 'El rey de Fifa' },
      { word: 'Knekro', hint: 'Leyenda de cartas' },
      { word: 'ElmiilloR', hint: 'Toxicidad de Lol' },
      { word: 'Werlyb', hint: 'León de Lol' },
      { word: 'Mixwell', hint: 'Poder de Valorant' },
      { word: 'Hitbox King', hint: 'Coleccionista de cartas' },
      { word: 'Paula Gonu', hint: 'Baile de fitness' },
      { word: 'Cristinini', hint: 'Conductora de esports' },
      { word: 'Biyín', hint: 'Viento de Twitch' }
    ] as GameWord[]
  },
  {
    id: 'memes',
    name: 'Memes',
    icon: '🎭',
    color: 'from-yellow-300 to-yellow-500',
    words: [
      { word: 'Doge', hint: 'Shiba millonario' },
      { word: 'Rickroll', hint: 'Trampa ochentera' },
      { word: 'Stonks', hint: 'Gráfico irónico' },
      { word: 'Cheems', hint: 'Amsiedad' },
      { word: 'Gigachad', hint: 'Mandíbula alfa' },
      { word: 'Pepe', hint: 'Rana miserable' },
      { word: 'Nyan Cat', hint: 'Arcoíris 8-bit' },
      { word: 'Harambe', hint: 'Incidente del zoo' },
      { word: 'Grumpy Cat', hint: 'Desagrado felino' },
      { word: 'Trollface', hint: 'Sonrisa arrugada' },
      { word: 'Success Kid', hint: 'Puño de playa' },
      { word: 'Bad Luck Brian', hint: 'Chaleco de brackets' },
      { word: 'Disaster Girl', hint: 'Sonrisa de fuego' },
      { word: 'Overly Attached Girlfriend', hint: 'Ojos abiertos novios' },
      { word: 'Scumbag Steve', hint: 'Gorra de cuadros' },
      { word: 'Drake Hotline', hint: 'Rechazo y aceptación' },
      { word: 'Distracted Boyfriend', hint: 'Mirada de reojo' },
      { word: 'Mocking Spongebob', hint: 'Letras intercaladas' },
      { word: 'Surprised Pikachu', hint: 'Boca abierta amarilla' },
      { word: 'Dat Boi', hint: 'Rana en monociclo' },
      { word: 'Kermit the Frog', hint: 'Taza de té' },
      { word: 'Roll Safe', hint: 'Dedo en sien' },
      { word: 'Evil Kermit', hint: 'Caperuza negra' },
      { word: 'Coffin Dance', hint: 'Ataúd rítmico' },
      { word: 'Wide Putin', hint: 'Caminata ancha' },
      { word: 'Hide the Pain Harold', hint: 'Sonrisa fingida' },
      { word: 'Wojak', hint: 'Calvo deprimido' },
      { word: 'Doomer', hint: 'Cigarrillo y capucha' },
      { word: 'Keyboard Cat', hint: 'Gato pianista' },
      { word: 'Longcat', hint: 'Gato estirado' },
      { word: 'Ceiling Cat', hint: 'Gato del techo' },
      { word: 'Pedobear', hint: 'Oso de peluche sospechoso' },
      { word: 'Chuck Norris', hint: 'Verdad absoluta' },
      { word: 'Gabe the Dog', hint: 'Ladrido rítmico' },
      { word: 'Walter the Dog', hint: 'Bull terrier redondo' },
      { word: 'Smudge the Cat', hint: 'Gato comiendo ensalada' },
      { word: 'Woman Yelling at Cat', hint: 'Grito en la mesa' },
      { word: 'Bernie Sanders', hint: 'Guantes de lana' },
      { word: 'Ricardo Milos', hint: 'Pañuelo rojo bailable' },
      { word: 'Shooting Stars', hint: 'Gordo volando' },
      { word: 'We Are Number One', hint: 'Villano de saxo' },
      { word: 'Crab Rave', hint: 'Cangrejos bailando' },
      { word: 'Sanic', hint: 'Erizo deforme' },
      { word: 'Ugandan Knuckles', hint: 'Do you know the way' },
      { word: 'Spoderman', hint: 'Araña deforme' },
      { word: 'Dolan Duck', hint: 'Pato deforme' },
      { word: 'Me Gusta', hint: 'Cara redonda de acuerdo' },
      { word: 'Yao Ming Meme', hint: 'Risa de reojo' },
      { word: 'Forever Alone', hint: 'Lágrima de piedra' },
      { word: 'Rage Guy', hint: 'Fffffffuuuuuuuuuuu' },
      { word: 'Cereal Guy', hint: 'Cereal en boca' },
      { word: 'Poker Face', hint: 'Boca lineal' },
      { word: 'Challenge Accepted', hint: 'Desafío aceptado' },
      { word: 'True Story', hint: 'Copa en mano' },
      { word: 'Okay Guy', hint: 'Cabeza agachada' },
      { word: 'LOL Guy', hint: 'Risa gigante inclinada' }
    ] as GameWord[]
  }
];

export const INITIAL_CONFIG = {
  minPlayers: 3,
  maxPlayers: 12,
  defaultPlayers: 3,
  defaultImpostors: 1,
  durations: [30, 60, 90, 120]
};
